#!/usr/bin/env bash
# A bash script that takes in three arguments and if valid transfers a file to a server

if [ $# != 4 ]; then
     	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3@$2": ~/  
fi
