#!/usr/bin/env bash
# A script for installing HAproxy and setting up load balancing
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y  ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo -e "
frontend http_front
\tbind *:80
\tstats uri /haproxy?stats
\tdefault_backend http_back

backend http_back
\tbalance roundrobin
\tserver 1646-web-01 34.75.46.132:80 check
\tserver 1646-web-02 104.196.16.10:80 check
" >> /etc/haproxy/haproxy.cfg
echo "
ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart


