#!/usr/bin/env bash
# A script for installing HAproxy and setting up load balancing
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y  ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo -e "
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 1646-web-01 34.75.46.132:80 check
\tserver 1646-web-02 104.196.16.10:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "
ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
