#!/usr/bin/env bash
# a simple FizzBozz script

for (( i=1; i<101; i++ ))
do
    if [ $i%3 -eq 0 ] && [ $i%5 -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $i%3 -eq 0 ]
	echo "Fizz"
    elif [ $i%5 -eq 0 ]
	echo "Buzz"
    else
	echo $i
fi
done
