#!/usr/bin/env bash
# A script to print numbers 1 - 20 and note lucky or not luck by nation

i=1
while [ $i -lt 20 ]
do
    if [ $i -eq 4 ]
    then
	echo $i
	echo "bad luck from China"
	i=$(( i+1 ))
    elif [ $i -eq 9 ]
    then
	echo $i
	echo "bad luck from Japan"
	i=$(( i+1 ))
    elif [ $i -eq 17 ]
    then
	echo $i
	echo "bad luck from Italy"
	i=$(( i+1 ))
    else
	echo $i
	i=$(( i+1 ))
fi
done
