#!/usr/bin/env bash
# A script to print numbers 1 - 20 and note lucky or not luck by nation

i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4 )
	    echo "bad luck from China"
	    i=$(( i+1 ));;
	9 )
	    echo "bad luck from Japan"
	    i=$(( i+1 ));;
	17 )
	    echo "bad luck from Italy"
	    i=$(( i+1 ));;
	* )
	    i=$(( i+1 ));;
esac
done
