#!/usr/bin/env bash
# Networking basics 2 question 2 change localhost and facebook ip addresses

cp /etc/hosts ~/hosts_updt
echo 127.0.0.2 localhost > ~/hosts_updt
echo 8.8.8.8 facebook.com >> ~/hosts_updt
cp -f  ~/hosts_updt /etc/hosts
