#!/usr/bin/env bash
# A script to install Apache and set an html page with Hello Holberton

sudo apt-get -y update
sudo apt-get -y install apache2
sudo echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf
sudo echo "Hello Holberton"
sudo service apache2 start
