#!/usr/bin/env bash
# A script to install Apache and set an html page with Hello Holberton

sudo apt-get -y update
sudo apt-get -y install apache2
sudo apt-get -y install apache2-utils
sudo echo "ServerName localhost" | sudo tee /etc/apache2/apache2.conf
sudo echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo service apache2 start
